name: Upload config

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure libffi
        shell: bash
        run: |
          cd deps/libffi
          ./configure --enable-static --disable-shared --disable-builddir --with-pic --build=i386-pc-mingw32
      - name: Archive build configuration
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            deps/libffi/fficonfig.h
            deps/libffi/include/ffi.h
            deps/libffi/include/ffitarget.h
