name: Upload config

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, x86]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure libffi
        run: |
          cd deps/libffi
          ./configure --enable-static --disable-shared --disable-builddir --with-pic
      - name: Archive build configuration
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            deps/libffi/fficonfig.h
            deps/libffi/include/ffi.h
            deps/libffi/include/ffitarget.h
